### ISSUE TITLE
[CVPR'24 Spotlight] State Space Models for Event Cameras

### ISSUE THREAD

**Issue by NikolaZubic** [Ruixxxx/Awesome-Vision-Mamba-Models#5]
Dear @Ruixxxx , our work has been a spotlight at CVPR 2024. We would like if you could add it to the list:

https://arxiv.org/abs/2402.15584
https://github.com/uzh-rpg/ssms_event_cameras

Best,
Nikola.

**Comment by Ruixxxx** [comment]
> Dear @Ruixxxx , our work has been a spotlight at CVPR 2024. We would like if you could add it to the list:
> 
> https://arxiv.org/abs/2402.15584 https://github.com/uzh-rpg/ssms_event_cameras
> 
> Best, Nikola.

Dear Nikola,

Congratulations on having your work highlighted at CVPR 2024, and thank you for sharing the details with us. We have now added your work to our list.

Best,
Rui
